Thread pool
Volodya-Petrov/Homework-sem3 pull request #3
Opened 2021-10-16 14:02 UTC by Volodya-Petrov

2021-11-02 19:03 UTC, Volodya-Petrov commented
Не знаю, почему не проходят билды, у себя дедлоки чота не могу поймать

2021-11-02 21:14 UTC, Volodya-Petrov commented
Я гений

2021-11-06 17:33 UTC, yurii-litvinov requested changes
По существу уже почти всё правильно, осталось добить детали.

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/TestForThreadPool/TestsForMyThreadPool.cs
> +        public void TestAfterShoutDownShouldCalculateSubmittedTasks()
Не поправлено

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/TestForThreadPool/TestsForMyThreadPool.cs
> +            Assert.Throws<ThreadInterruptedException>(() => threadPool.Submit(functions[0]));
ThreadInterruptedException тут неуместен, это системное исключение. Тут правильнее InvalidOperationException

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/TestForThreadPool/TestsForMyThreadPool.cs
> +            IMyTask<string>[] continueTasks = new IMyTask<string>[countOfTasks];
```suggestion
            var continueTasks = new IMyTask<string>[countOfTasks];
```

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/TestForThreadPool/TestsForMyThreadPool.cs
> +        public void TestAfterShoutDownUCantSumbitContinueWith()
Опечатки не поправлены

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/TestForThreadPool/TestsForMyThreadPool.cs
> +    }
Надо хоть один тест на обращение из нескольких потоков к самому тредпулу. Проверить, что не будет дедлоков при одновременном Submit и Shutdown, или Shutdown и ContinueWith, например.

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/WorkWithThreadPool/MyThreadPool.cs
> +        private CancellationTokenSource _cancellationToken;
Некоторые поля называются с подчёркивания, некоторые нет, надо какой-то один стиль выбрать (по мне так лучше без подчёркивания, IDE и так знает, что поля --- это поля).

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/WorkWithThreadPool/MyThreadPool.cs
> +        /// <summary>
```suggestion
        private int tasksCount; 
        
        /// <summary>
```

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/WorkWithThreadPool/MyThreadPool.cs
> +            public bool IsCompleted { get => _isCompleted; }
```suggestion
            public bool IsCompleted => _isCompleted;
```
Это то же самое, но писать меньше

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/WorkWithThreadPool/MyThreadPool.cs
> +                    _result = task();
Тут тоже надо где-то забыть про _result, как в Lazy. Чтобы сборщик мусора мог его собрать.

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/WorkWithThreadPool/MyThreadPool.cs
> +                    _continueTasks.Enqueue(newContinueTask.Run);
Если в этот момент произойдёт 90-я строчка, то таска добавится в очередь, но никто никогда её оттуда не достанет, дедлок :) Надо синхронизировать ContinueWith и ту часть Run, что отвечает за исполнение continuation-ов.

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/WorkWithThreadPool/MyThreadPool.cs
> +                    }, _threadPool);
Это вы с Иваном Москаленко вместе делали, что ли? :) Копипаст развели. Лучше бы с Анатолия Владимировича скатали :)

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/WorkWithThreadPool/MyThreadPool.cs
> +                    Interlocked.Increment(ref _threadPool.tasksCount);
Это какое-то нарушение инкапсуляции, тредпул мог бы и сам отвечать за свои поля.

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/WorkWithThreadPool/MyThreadPool.cs
> +            }
```suggestion
                _cancellationToken.Cancel();
            }
```

2021-11-06 17:33 UTC, yurii-litvinov commented on WorkWithThreadPool/WorkWithThreadPool/Program.cs
> +        }
Это не надо :)

2021-11-14 11:59 UTC, yurii-litvinov approved these changes
Теперь всё ок вроде. Зачтена.

2021-11-14 11:59 UTC, yurii-litvinov commented on WorkWithThreadPool/TestForThreadPool/TestsForMyThreadPool.cs
> +            threadPool.Shutdown();
Непоказательно, потому что задачи могли успеть посчитаться ещё даже до того, как этот тест запустился. Тут разумнее было бы поставить на тредпул задачу, заблокировать её на ManualResetEvent, вызвать Shutdown и отпустить ManualResetEvent. Тогда задача точно должна начаться только после Shutdown

2021-11-14 11:59 UTC, yurii-litvinov commented on WorkWithThreadPool/WorkWithThreadPool/MyThreadPool.cs
> +                lock (threadPool.cancellationToken)
Блокировать вообще весь тредпул на всё время ContinueWith слишком расточительно. На самом деле, если isCompleted, то тредпул сам бросит исключение, можно не синхронизироваться вообще (Submit потокобезопасный по условию). Реально проверять на IsCancellationRequested надо только при добавлении newContinueTask (даже создание можно не в критической секции делать).

2021-11-14 12:41 UTC, merged